### ISSUE TITLE
Missing libacc_local_server.a

### ISSUE THREAD

**Issue by force-e** [sparkfunX/A111_Pulsed_Radar_Breakout#2]
Hey guys, first of all thanks for the work on this!
I've followed the tutorial but after copying the rules/source contents to the proper folders in the SDK  and running make, I get the following:

`make: *** No rule to make target 'libacc_local_server.a', needed by 'out/sparkx_envelope_service_example'.  Stop.`

After comparing the original rules with the sparkfun rules, I see that you are expecting the following lib files:
- libacc_local_server.a
- libacc_message_driver_dummy.a

However, these are not present in the lib folder of the SDK.

Does this mean they have removed some files from the lib folder in the SDK by which the Sparkfun tutorial is no longer compliant? I received  acconeer_evk_service_linux_armv7l_xc111_r4a_xr111-3_r1c_a111_r2c_v1_3_6.zip from Acconeer, while the tutorial mentions v1_3_5?
If I leave the sparkfun files out (rules/source), the SDK compiles without problems.

Any help would be appreciated!

**Comment by uscgongjianxin** [comment]
I was unable to build the examples too. The example code provided by Sparkfun was written for an earlier A1 SDK version (1.3.5) and the newer version (1.3.9) might have changed enough that it breaks the build. Does someone have the A1 SDK 1.3.5 on the Acconeer website? Or does someone have a runnable example code to use SDK?

**Comment by jkumaran** [comment]
I made a fork with updates in all 6 files of Software/sparkx-sdk-addon/ folder to support v1.3.9:
https://github.com/jkumaran/A111_Pulsed_Radar_Breakout
This fixed the problem and I was able to observe the radar results.

**Comment by jimblom** [comment]
This issues should be resolved with the latest commit, which brings the source/makefiles up to SDK 1.3.9. Feel free to re-open if you have any similar issues.
