### ISSUE TITLE
make error using spark example code on A1 SDK 1.3.9

### ISSUE THREAD

**Issue by uscgongjianxin** [sparkfunX/A111_Pulsed_Radar_Breakout#3]
I found the example code provided by Sparkfun was written for an earlier A1 SDK version (1.3.5) and the newer version (1.3.9) might have changed enough that it breaks the build. After I type "make" n terminal, I met this problem.

pi@raspberrypi:~/a111/evk_service_linux_armv7l_xc111_r4a_xr111-3_r1c_a111_r2c $ make
    Linking sparkx_envelope_service_example
lib/libacconeer_a111_r2c.a(acc_sensor_driver.o): In function `acc_hal_sensor_device_register_isr':
/home/anders/repos/sw-main/acconeer/sensor/sensor_driver/acc_sensor_driver.c:157: undefined reference to `acc_board_register_isr'
collect2: error: ld returned 1 exit status
rule/makefile_build_example_service_envelope_rpi_sparkx.inc:10: recipe for target 'out/sparkx_envelope_service_example' failed
make: *** [out/sparkx_envelope_service_example] Error 1

I cannot find the directory shown in the error message.
/home/anders/repos/sw-main/acconeer/sensor/sensor_driver/acc_sensor_driver.c

Does someone successfully build the program and get the radar data?

**Comment by jkumaran** [comment]
I made a fork with updates in all 6 files of Software/sparkx-sdk-addon/ folder:
https://github.com/jkumaran/A111_Pulsed_Radar_Breakout
This fixed the problem and I was able to observe the radar results.

**Comment by seasilvia** [comment]
I'm doing general troubleshooting, my board might just be dead.  I installed this code and make worked successfully:

```
pi@raspberrypi:~/a111/evk_service_linux_armv7l_xc112 $ make
    Compiling acc_board_rpi_sparkx.c
    Linking sparkx_envelope_service_example
    Linking sparkx_envelope_iq_example
    Linking sparkx_power_bins_example
    Compiling sparkx_detector_distance.c
    Linking sparkx_detector_distance
```

However, running the example service, I got "could not determine version:

```
Acconeer software version v1.3.9
Acconeer RSS version 1.0
13:27:03.832 [ 1669] (I) (rss): Radar system services activated
13:27:03.838 [ 1669] (I) (core_a111_r2c): Unknown sensor version 0x0000
13:27:03.838 [ 1669] (E) (session_sweep_and_processing): Could not determine version for sensor 1
13:27:03.838 [ 1669] (E) (session_sweep_and_processing): Sensor 1 not prepared
13:27:03.838 [ 1669] (I) (session_sweep_and_processing): acc_session_sweep_and_processing_destroy: Destroy confirmed
13:27:03.838 [ 1669] (E) (service_envelope): Session not created
acc_service_create failed
execute_envelope_with_blocking_calls() => (1) Failure unspecified
```

Any ideas? Could I have something misconfigured?

**Comment by jimblom** [comment]
@jkumaran Thanks for your help. I've committed some changes that mostly reflect what you've done in your fork in the latest commit -- b114e95.

@seasilvia Can you give it a try with the latest updates to the include/source files?

**Comment by jimblom** [comment]
@seasilvia I just pushed some changes in commit c4784f2 that should make the makefile rules and examples compatible with A111 SDK v1.3.11. Give it a try and see if it fixes your board. Feel free to re-open if it's still giving you trouble.

@jkumaran -- Sorry I didn't check this issue first to find your fixes... Thanks for your help!
