### ISSUE TITLE
make error using spark example code on A1 SDK 1.3.11

### ISSUE THREAD

**Issue by hpritchett** [sparkfunX/A111_Pulsed_Radar_Breakout#5]
I am getting this error when I run make:
make: *** No rule to make target 'out/example_service_envelope.o', needed by 'out/sparkx_envelope_service_example'.  Stop.

Using the following sdk:
acconeer_evk_service_linux_armv7l_xc111_r4a_xr111-3_r1c_a111_r2c_v1_3_11

The build only fails if I add the A111_Pulsed_Radar_Breakout software addon.
Does anyone have SDK 1.3.9? Or know what I need to do to fix this?

**Comment by jimblom** [comment]
Sorry about the delay. I've made some fixes to the rules and board source files in commit c4784f2.

All examples should be compatible with the latest A111 SDK: v1.3.11.
